In [94]:
import pandas as pd
import numpy as np

In [95]:
import os

cwd = os.getcwd()
temperature_path = os.path.join(cwd, "raw/Average Temperature of Cities.csv")
country_codes_path = os.path.join(cwd,"raw/ISO-3166-Countries-with-Regional-Code.csv")

In [96]:
temperatures = pd.read_csv(temperature_path)
print(temperatures.head())
len(temperatures)

   Country         City           Jan           Feb           Mar  \
0  Algeria      Algiers  11.2\n(52.2)  11.9\n(53.4)  12.8\n(55.0)
1  Algeria  Tamanrasset  12.8\n(55.0)  15.0\n(59.0)  18.1\n(64.6)
2  Algeria      Reggane  16.0\n(60.8)  18.2\n(64.8)  23.1\n(73.6)
3   Angola       Luanda  26.7\n(80.1)  28.5\n(83.3)  28.6\n(83.5)
4    Benin      Cotonou  27.3\n(81.1)  28.5\n(83.3)  28.9\n(84.0)

            Apr           May           Jun            Jul            Aug  \
0  14.7\n(58.5)  17.7\n(63.9)  21.3\n(70.3)   24.6\n(76.3)   25.2\n(77.4)
1  22.2\n(72.0)  26.1\n(79.0)  28.9\n(84.0)   28.7\n(83.7)   28.2\n(82.8)
2  27.9\n(82.2)  32.2\n(90.0)  36.4\n(97.5)  39.8\n(103.6)  38.4\n(101.1)
3  28.2\n(82.8)  27.0\n(80.6)  23.9\n(75.0)   22.1\n(71.8)   22.1\n(71.8)
4  28.6\n(83.5)  27.8\n(82.0)  26.5\n(79.7)   25.8\n(78.4)   25.6\n(78.1)

            Sep           Oct           Nov           Dec          Year  \
0  23.2\n(73.8)  19.4\n(66.9)  15.2\n(59.4)  12.1\n(53.8)  17.4\n(63.3)
1  26.5\n(79.7)  22.4\n(72.3)  17.3\n(63.1)  13.9\n(57.0)  21.7\n(71.1)
2  35.5\n(95.9)  29.2\n(84.6)  22.0\n(71.6)  17.8\n(64.0)  28.3\n(82.9)
3  23.5\n(74.3)  25.2\n(77.4)  26.7\n(80.1)  26.9\n(80.4)  25.8\n(78.4)
4  26.0\n(78.8)  26.7\n(80.1)  27.6\n(81.7)  27.3\n(81.1)  27.2\n(81.0)

  Continent
0    AFRICA
1    AFRICA
2    AFRICA
3    AFRICA
4    AFRICA

451

In [97]:
country_codes = pd.read_csv(country_codes_path)
print(country_codes.head())
len(country_codes)

             name alpha-2 alpha-3  country-code     iso_3166-2   region  \
0     Afghanistan      AF     AFG             4  ISO 3166-2:AF     Asia
1   Åland Islands      AX     ALA           248  ISO 3166-2:AX   Europe
2         Albania      AL     ALB             8  ISO 3166-2:AL   Europe
3         Algeria      DZ     DZA            12  ISO 3166-2:DZ   Africa
4  American Samoa      AS     ASM            16  ISO 3166-2:AS  Oceania

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0
1  Northern Europe                 NaN        150.0            154.0
2  Southern Europe                 NaN        150.0             39.0
3  Northern Africa                 NaN          2.0             15.0
4        Polynesia                 NaN          9.0             61.0

   intermediate-region-code
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN

249

In [98]:
# rename some country names:
country_codes.replace(to_replace="Türkiye", value="Turkey",inplace=True)
country_codes.replace(to_replace="United Kingdom of Great Britain and Northern Ireland", value="United Kingdom",inplace=True)
country_codes.replace(to_replace="United States of America", value="United States",inplace=True)
country_codes.replace(to_replace="Russian Federation", value="Russia",inplace=True)
country_codes.replace(to_replace="Netherlands, Kingdom of the", value="Netherlands",inplace=True)
country_codes.replace(to_replace="Czechia", value="Czech Republic",inplace=True)
country_codes.replace(to_replace="Iran, Islamic Republic of", value="Iran",inplace=True)
country_codes.replace(to_replace="Korea, Democratic People's Republic of", value="North Korea",inplace=True)
country_codes.replace(to_replace="Korea, Republic of", value="South Korea",inplace=True)
country_codes.replace(to_replace="Viet Nam", value="Vietnam",inplace=True)
country_codes.replace(to_replace="Taiwan, Province of China", value="Taiwan",inplace=True)
country_codes.replace(to_replace="Tanzania, United Republic of", value="Tanzania",inplace=True)
country_codes.replace(to_replace="Côte d'Ivoire", value="Ivory Coast",inplace=True)
country_codes.replace(to_replace="Syrian Arab Republic", value="Syria",inplace=True)
country_codes.replace(to_replace="Congo, Democratic Republic of the", value="Democratic Republic of the Congo",inplace=True)
country_codes.replace(to_replace="Lao People's Democratic Republic", value="Laos",inplace=True)
country_codes.replace(to_replace="Bolivia, Plurinational State of", value="Bolivia",inplace=True)
country_codes.replace(to_replace="Falkland Islands (Malvinas)", value="Falkland Islands",inplace=True)
country_codes.replace(to_replace="Venezuela, Bolivarian Republic of", value="Venezuela",inplace=True)
country_codes.replace(to_replace="Moldova, Republic of", value="Moldova",inplace=True)

temperatures.replace(to_replace="Republic of the Congo", value="Democratic Republic of the Congo", inplace=True)
temperatures.replace(to_replace="Cape Verde", value="Cabo Verde", inplace=True)
temperatures.replace(to_replace="The Gambia", value="Gambia", inplace=True)
temperatures.replace(to_replace="East Timor", value="Timor-Leste", inplace=True)
temperatures.replace(to_replace="United Arab\nEmirates", value="United Arab Emirates", inplace=True)
temperatures.replace(to_replace="Macedonia", value="North Macedonia", inplace=True)
temperatures.replace(to_replace="The Bahamas", value="Bahamas", inplace=True)
temperatures.replace(to_replace="Saint Pierre\nand Miquelon", value="Saint Pierre and Miquelon", inplace=True)

In [99]:
temperature_with_country_codes = temperatures.merge(country_codes, left_on='Country', right_on='name', how='left')

In [100]:
# there should not be any null values
nan_rows = temperature_with_country_codes[temperature_with_country_codes['alpha-2'].isnull()]
nan_rows

Empty DataFrame
Columns: [Country, City, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec, Year, Continent, name, alpha-2, alpha-3, country-code, iso_3166-2, region, sub-region, intermediate-region, region-code, sub-region-code, intermediate-region-code]
Index: []

[0 rows x 27 columns]

In [101]:
# remove fahrenheit temperatures
temperature_with_country_codes = temperature_with_country_codes.replace(to_replace=r'([\d.]+)\n\([\d.]+\)', value=r'\1', regex=True)
temperature_with_country_codes

,Country,City,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,...,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Algeria,Algiers,11.2,11.9,12.8,14.7,17.7,21.3,24.6,25.2,...,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
1,Algeria,Tamanrasset,12.8,15.0,18.1,22.2,26.1,28.9,28.7,28.2,...,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
2,Algeria,Reggane,16.0,18.2,23.1,27.9,32.2,36.4,39.8,38.4,...,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
3,Angola,Luanda,26.7,28.5,28.6,28.2,27.0,23.9,22.1,22.1,...,AO,AGO,24,ISO 3166-2:AO,Africa,Sub-Saharan Africa,Middle Africa,2.0,202.0,17.0
4,Benin,Cotonou,27.3,28.5,28.9,28.6,27.8,26.5,25.8,25.6,...,BJ,BEN,204,ISO 3166-2:BJ,Africa,Sub-Saharan Africa,Western Africa,2.0,202.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,Peru,Lima,22.1,22.7,22.2,20.6,18.8,17.5,16.7,16.2,...,PE,PER,604,ISO 3166-2:PE,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
447,Peru,Piura,26.8,27.8,27.8,26.6,24.5,22.9,21.8,21.9,...,PE,PER,604,ISO 3166-2:PE,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
448,Suriname,Paramaribo,26.0,26.0,26.2,26.7,26.5,26.5,26.7,27.4,...,SR,SUR,740,ISO 3166-2:SR,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
449,Uruguay,Montevideo,23.0,22.5,20.6,17.2,14.0,11.1,10.9,11.7,...,UY,URY,858,ISO 3166-2:UY,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
450,Venezuela,Caracas,20.2,20.8,21.7,22.7,23.2,22.6,22.2,22.3,...,VE,VEN,862,ISO 3166-2:VE,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0

In [102]:
temperature_with_country_codes = temperature_with_country_codes[['Country',
                                                                 'City',
                                                                 'Jan',
                                                                 'Feb',
                                                                 'Mar',
                                                                 'Apr',
                                                                 'Jun',
                                                                 'Jul',
                                                                 'Aug',
                                                                 'Sep',
                                                                 'Oct',
                                                                 'Nov',
                                                                 'Dec',
                                                                 'Year',
                                                                 'alpha-2',
                                                                 'alpha-3',
                                                                 'region',
                                                                 'sub-region']]

In [103]:
temperature_with_country_codes.to_csv(os.path.join(cwd,"temperature_cities.csv"),index=False, header=['country',
                                                                 'city',
                                                                 'jan',
                                                                 'feb',
                                                                 'mar',
                                                                 'apr',
                                                                 'jun',
                                                                 'jul',
                                                                 'aug',
                                                                 'sep',
                                                                 'oct',
                                                                 'nov',
                                                                 'dec',
                                                                 'year_avg',
                                                                 'alpha_2',
                                                                 'alpha_3',
                                                                 'region',
                                                                 'sub_region'])